export default {
    ON_LOAD_DATA: "ON_LOAD_DATA",
    ON_CHANGES_CITY_NAME: "ON_CHANGES_CITY_NAME",
    ON_CHANGE_CURRENT_DEATILS: "ON_CHANGE_CURRENT_DEATILS",
    ON_ADD_CUREENT_CITY_NAME: "ON_ADD_CUREENT_CITY_NAME",
    ON_CHANGE_ZIP_CODE: 'ON_CHANGE_ZIP_CODE',
    ON_CLICK_SEARCH: 'ON_CLICK_SEARCH',
    ON_ERROR_MSG_SHOW: 'ON_ERROR_MSG_SHOW',
}
